name: PR Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'src/**.json'
      - 'src/**.png'

permissions:
  contents: read

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build and Test
        uses: gradle/gradle-command-action@v2
        with:
          arguments: |
            checkLicenses
            detekt
            :buildLogic:convention:checkLicenses
            :buildLogic:convention:detekt
            build
